"""empty message

Revision ID: 9dc5075cbdc5
Revises: 46d0f3c3586f
Create Date: 2017-08-12 23:13:45.626498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dc5075cbdc5'
down_revision = '46d0f3c3586f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('question', 'context')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('context', mysql.TEXT(), nullable=False))
    op.drop_column('question', 'content')
    # ### end Alembic commands ###
